# Generated by Django 5.0.6 on 2024-07-09 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_mambership_customer_membership'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='payment_choices',
            new_name='payment_status',
        ),
    ]
