# Generated by Django 5.0.6 on 2024-07-09 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_order_order_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='unite_price',
            new_name='unit_price',
        ),
    ]
